### ISSUE TITLE
Quantity buttons appearance

### ISSUE THREAD

**Issue by mathew07** [woothemes/WooCommerce-Quantity-Increment#2]
I upgraded my woocommerce store but I don't wan't to resign from quantity plus/minus buttons. I installed this plugin but the quantity buttons doesn't looks like my old ones. You can see my old quantity button here http://www.dalbeshop.eu (this is my old testing site, but still with great quantity buttons). Now at my main site http://www.dalbeshop.pl I have really bad looking buttons and completely doesn't know how to fix them. I think that it is css settings issue, but I can't change it to the previous version (don't know how). Pleas help me achieve that, Mat.

**Comment by bryceadams** [comment]
Hi @mathew07. It is a theme CSS issue but it's our Storefront so we can have a look.

@jameskoster - did we have specific quantity button styling in storefront that has been removed? Or is it my fault?

**Comment by jameskoster** [comment]
All styling of those elements has been removed in Storefront 1.3.0. The plugin looks like it uses the CSS that used to be in WooCommerce core, so it's going to look different regardless.

@mathew07 to make it look like the old version you'll need the dequeue the plugin CSS and run your own.

**Comment by mathew07** [comment]
Hi guys, thank's for your responses. I am not as good in coding, I'm learning everything by myself. All I know is that before upgrade the quantity buttons looks better then now. And unfortunatelly I don't know how to write the css code to get previous look. I tried but i failed. This is the present look http://i62.tinypic.com/xpxwtz.png and this is the previous look http://i61.tinypic.com/2zoi0pg.png. It is a shame that upgrade instalation doesn't have option to choose changes (for example choose "not to remove quantity buttons" :) ). Could you guys help me with this?

**Comment by bradleysa** [comment]
I prefer the UX / UI / styling of the old buttons with Storefront, which have nice big boxes on each side of the number input box for - and +.
https://cloudup.com/cGWVBI3nQB6
I feel the new buttons are less user-friendly and less attractive.
https://cloudup.com/cPjUIVtIR6j

**Comment by jameskoster** [comment]
If you just dequeue `wcqi-css` the appearance will revert to the default in Storefront.

**Comment by bradleysa** [comment]
I tried to accomplish this after reading documentation and tutorials, but I can't figure out how to dequeue `wcqi-css`. Would you please supply me with a snippet or more information on how to do this? I want to learn and understand hooks better, so I tried on my own before asking for help.

**Comment by bryceadams** [comment]
Hey Brad,

Try add the following code to the 'custom functions' area of your `functions.php` file (or use a plugin like **Functionality** - https://wordpress.org/plugins/functionality/):

```
add_action( 'wp_enqueue_scripts', 'wcs_dequeue_quantity' );
function wcs_dequeue_quantity() {
    wp_dequeue_style( 'wcqi-css' );
}
```

**Comment by bradleysa** [comment]
Thank you so much bryce. I really appreciate your support.

**Comment by mathew07** [comment]
@jameskoster, @bradleysa 

Great job guys! Thank you very much! Everything works great. 

I will share this solution here: https://wordpress.org/support/plugin/woocommerce-quantity-increment to help more people.

**Comment by bryceadams** [comment]
😇
