### ISSUE TITLE
Quantity buttons appearance vol.2 

### ISSUE THREAD

**Issue by mathew07** [woothemes/WooCommerce-Quantity-Increment#3]
Guys I'm sorry but I must re-open "quantity buttons issue". Bad luck for me. 

After resolving previous thread everything works fine and looks really good ...  until I updated theme - storefront to 1.3.0. 

After update my quantity buttons looks like this: 

![1](https://cloud.githubusercontent.com/assets/10978798/6231623/2c69769e-b6c7-11e4-8f48-e8230acf790c.png) 

there is some additional quantity buttons inside number box. 

Using css I can made them looks like this: 

![2](https://cloud.githubusercontent.com/assets/10978798/6231647/498654a4-b6c7-11e4-8527-4fd4dbbe3397.png) 

but there is still hover blue colour (which i don't know how to delete - there is no such line in css style) and additional quantity buttons inside box. 

My previous buttons (before any upgrade - storefront or woocommerce):

![3](https://cloud.githubusercontent.com/assets/10978798/6231702/9b59100a-b6c7-11e4-83ff-cde2c5e4df72.png)

Before updating theme I had such looking buttons and it was great but theme upgrade rearrange them. I'm sorry for my binding, please give me some advice :)

**Comment by mathew07** [comment]
Anybody here? ..

**Comment by mikejolley** [comment]
Tested and working in storefront v2 https://dl.dropboxusercontent.com/s/gqv7z7lbv1jfi7o/2016-07-25%20at%2011.48.png?dl=0
